name: Build deb package
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add description
      run: |
        git tag v6.9.0
    - name: Download apt-get deiendencies
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y purge unattended-upgrades
        sudo apt-get -y update
        sudo apt-get -y install bison flex devscripts debhelper-compat libbsd-dev dh-package-notes
    - name: Enable src repos
      run: |
        sudo sed -i 's/# deb-src/deb-src/' /etc/apt/sources.list
        sudo apt update
    - name: Import debian rules
      run: |
        git remote add debian https://salsa.debian.org/debian/iproute2.git
        git fetch debian
        git checkout debian/$(git describe --tags | tr -d 'v')-1 -- debian
        sudo apt build-dep iproute2
    - name: Build deb
      run: dpkg-buildpackage -b -rfakeroot -us -uc -d
    - name: Zip artifacts
      run: |
        mkdir -p iproute2-l4s
        mv -t iproute2-l4s ../*.deb
        zip -r iproute2-l4s.zip iproute2-l4s
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iproute2-l4s
        path: iproute2-l4s
    - name: Release tip build
      uses: pyTooling/Actions/releaser@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: master-build
        files: |
          iproute2-l4s.zip
